# Generated by Django 4.1.4 on 2022-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=200)),
                ('dedicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
