# Generated by Django 4.1.4 on 2022-12-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_cursos_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('curso', models.CharField(max_length=200)),
            ],
        ),
    ]
