# Generated by Django 4.1.4 on 2022-12-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_tutores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='direccion',
            new_name='provincia',
        ),
    ]
