# Generated by Django 4.1.4 on 2022-12-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_rename_direccion_alumnos_provincia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Tutores',
            new_name='Tutor',
        ),
    ]
